version: '3.7'
services:
  kms-db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: kms-db
    ports:
      - "3308:3306"
    volumes:
      - .database:/var/lib/mysql